### ISSUE TITLE
1.1 beta 2 "...does not have a valid header" error

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#137]
Only occurs when first installing and clicking the activate link. Not when returning to the plugins page and activating there. That works fine.

**Comment by brashrebel** [comment]
Did NOT receive the same result when changed the .zip name to simply render.zip instead of render-1-1-beta2.zip. The former worked fine while the latter produced the above mentioned error.

**Comment by joelworsham** [comment]
Not surprising. For some reason WordPress is very picky about directory names. I wouldn't necessarily consider trying to install the entire master zip a necessity like that. But for build, it should definitely work
