### ISSUE TITLE
Query shortcode include and exclude fields not working in customizer

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#138]
When using the customizer to add a query shortcode, the include and exclude attribute fields just show a spinning timer for each and can't be used. The output seems to work fine.

Not sure if it is related, but the logic shortcode seems to have some buggy behavior. I'm still in the customizer and selecting an Argument One requires me to actually hold down the select field, otherwise the options don't show PLUS the parameter input just shows the spinny icon and is not usable.

This was test on two RBW staging sites.

**Comment by joelworsham** [comment]
This is a bug I'm pushing now to fix actually. Here 66e91b9
