### ISSUE TITLE
Deleting all placeholder content in a column deletes the column

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#140]
I was observing @bigactual attempting to use the columns in v. 1.1beta2 and we encountered several usability issues, this being the biggest.

When columns are inserted, they contain placeholder content. The content seems to not allow for select all deletion but deleting single characters at a time with the delete key works although, as mentioned in the title, when the last character is deleted, the column goes kablooey. In order to insert content into the column (in our case, a Gravity Form) we had to leave a single character in the column, insert our shortcode before it and then delete the extra character. Then everything was fine.

**Comment by joelworsham** [comment]
Fixed in Develop branch (didn't mention in commit msg though)
