### ISSUE TITLE
Better TinyMCE icon

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#64]
The `<>` seems like the wrong choice at this point. There are a few Dashicons that I think could work, or we could just make one of the Render logo or something. I think `dashicons-welcome-view-site` - f115 could work....

**Comment by joelworsham** [comment]
We could use a custom icon

**Comment by brashrebel** [comment]
Make it so.

**Comment by joelworsham** [comment]
https://www.dropbox.com/s/xekw30m4ou2gf29/Screenshot%202015-01-13%2012.06.44.png?dl=0
