### ISSUE TITLE
Way to trigger TinyMCE refresh from extension

### ISSUE THREAD

**Issue by brashrebel** [brashrebel/render#65]
Easiest to describe in the use case I'm working with. EDD creates a button which sits above TinyMCE. That button is used for inserting one of the 13 available EDD shortcodes. When it is used, a shortcode is inserted and is seen in the normal `[shortcode]` style, inline. But when something is done that triggers the TinyMCE refresh such as switching to text and back, using the Render modal or the refresh button you made, the shortcode is then rendered in the editor.

It would be nice if there were a way to trigger that refresh on other actions like the default EDD button. However, I'm not sure whether this will open a can of worms.

Related to this is the discussion on what to do by default with these buttons that other plugins create for their shortcodes. We could:
- Do nothing with them
- Remove them entirely
- Remove them with an option to add them back
- Leave them with an option to remove them
- Modify them

I have a feeling it may be a case-by-case issue where some may be better removed and some should be left alone. Again, I'm getting off topic. Sorry.

**Comment by joelworsham** [comment]
In order to refresh the TinyMCE, call `Render_tinymce.loadVisual();` from your JavaScript

**Comment by joelworsham** [comment]
Scratch, that. I've added a very simple function to call now. Call `RenderRefreshTinyMCE()`
