### ISSUE TITLE
EDD licensing not working on mother site

### ISSUE THREAD

**Issue by joelworsham** [brashrebel/render#89]
Activate / Deactivate works great in the plugin itself, but deactivating is not reflected on realbigplugins.com

**Comment by brashrebel** [comment]
Does it have anything to do with this notice I just got in the dashboard?
![screenshot 2015-01-19 17 26 54](https://cloud.githubusercontent.com/assets/4993131/5808899/8dad9aa8-a000-11e4-827f-e17e494e42eb.png)

**Comment by joelworsham** [comment]
That issue has been resolved by updating all EDD plugins.

I'm in communication with EDD support trying to get to the bottom of this.
