### ISSUE TITLE
Conditional attributes

### ISSUE THREAD

**Issue by joelworsham** [brashrebel/render#90]
Basically like Gravity Forms conditional logic. If att A = X, show att B.

This would be massively useful.

**Comment by brashrebel** [comment]
I'm wondering if another use case I encountered a need for would apply here. I think so. In the Woocommerce add on, I encountered a number of shortcodes which allow for product lists to be filtered by ID or by SKU. It would be nice if there were a way to make it more obvious to users that the two attributes are mutually exclusive. I'm not sure how to represent this but I want to explore it.
